services:

  dockmon:
    image: darthnorse/dockmon:latest
    container_name: dockmon
    restart: unless-stopped
    ports:
      - "8200:443"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./dockmon_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
